---

- hosts: all
  become: true
  tasks:

  - name: create AlCapone user
    tags: always
    user:
      name: AlCapone
      groups: root

  - name: add ssh key for AlCapone
    tags: always
    authorized_key:
      user: AlCapone
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIK+u8SO4BL7tw8cGjeQw26ZV0OUxK/J3R8IE4Kt+OWb ansible"

  - name: add sudoers file for AlCapone
    tags: always
    copy:
      src: sudoer_AlCapone
      dest: /etc/sudoers.d/AlCapone
      owner: root
      group: root
      mode: 0440
