---

- hosts: all
  become: true
  tasks:

  - name: create MickeyD user
    tags: always
    user:
      name: MickeyD
      groups: root

  - name: add ssh key for MickeyD
    tags: always
    authorized_key:
      user: MickeyD
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIK+u8SO4BL7tw8cGjeQw26ZV0OUxK/J3R8IE4Kt+OWb ansible"

  - name: add sudoers file for MickeyD
    tags: always
    copy:
      src: sudoer_MickeyD
      dest: /etc/sudoers.d/MickeyD
      owner: root
      group: root
      mode: 0440
