---

- hosts: all
  become: true
  tasks:

  - name: install apache2 package
    yum:
      name: httpd

  - name: copy default html file for site
    tags: httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
