- name: add ssh key for AlCapone
  authorized_key:
    user: AlCapone
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIK+u8SO4BL7tw8cGjeQw26ZV0OUxK/J3R8IE4Kt+OWb ansible"

- name: generate sshd_config file from template
  tag: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd
